### ISSUE TITLE
ROS2 foxy /set_entity_state

### ISSUE THREAD

**Issue by pennergame** [dfki-ric-underactuated-lab/mimpc#1]
Hey Franek,

did you solved the issue ?

https://github.com/ros-simulation/gazebo_ros_pkgs/issues/838

Which file to include the /set_entity_state plugin?

Thank you so much :)

**Comment by FranekStark** [comment]
@pennergame, I think the solution was to use another plugin, which offered a similar service. Unfortunately, I forgot the name as we completely stopped using GAZEBO.
